### ISSUE TITLE
Pressing enter doesn't work when searching for a book

### ISSUE THREAD

**Issue by chaaals** [wasimreja/book-finder#1]
## Describe the Bug 🐛

Hey! I noticed it while testing your app. Pressing enter redirects the user to another path. Searching only works when you manually click on search.

**To Reproduce**

1. Go to search page
2. Type a book or author
3. Press enter
4. After pressing enter, it doesn't actually search for the book but rather redirects the user to another path

**Expected behavior**
After pressing enter, it should also search for the book.

**Screenshots**
Pressing enter redirects me to this page: 
![image](https://user-images.githubusercontent.com/70326902/193419257-0c0eab61-457e-42c3-b159-fd74c4a32605.png)

**Additional context**
Can I take over in solving this issue? Thanks! @wasimreja

**Comment by Bibhavshah** [comment]
It works fine, I tried
`

**Comment by wasimreja** [comment]
@chaaals go ahead

**Comment by chaaals** [comment]
> @chaaals go ahead

thanks! please assign this issue to me <3

**Comment by chaaals** [comment]
@wasimreja heyy, thanks for merging my change! I just noticed that labels in your repo has a typo. Instead of `hacktoberfest` , you  entered `hactoberfest`

**Comment by ManavMalhotra** [comment]
I don't think we should console.log('working') and book list in console
