### ISSUE TITLE
UI Enhancement

### ISSUE THREAD

**Issue by kushaljgec2025** [wasimreja/book-finder#103]
### Is your feature request related to a problem? Please describe.

The UI of the website is so simple. So I want to beautify the UI. I want to work on that

### Describe the solution you'd like

I can make the background better with a cool theme. And also can add a light-night button. And so on.

### Describe alternatives you've considered

I can make the background better with a cool theme. And also can add a light-night button. And so on.

**Comment by KaxitPandya** [comment]
@wasimreja I Think I Can Modify The UI to a Great Extend, Please Assign This Task to me

**Comment by wasimreja** [comment]
@KaxitPandya best of luck!
