### ISSUE TITLE
Search Result Card UI Redesign

### ISSUE THREAD

**Issue by AbirSantra** [wasimreja/book-finder#106]
### Is your feature request related to a problem? Please describe.

Currently, the search result cards show I bit too much information about the book at once. This seems to be a bit overwhelming for the user. Also, the user is able to see fewer results on the screen at once since each book is having too long descriptions and they have varying lengths. Also, the card's UI can be improved a bit.

![Uploading image.png…]()

### Describe the solution you'd like

I would like to redesign the search result cards and make them a bit smaller and more concise so that more results can be viewed at once. Also, the description of the book will be limited to 100 characters with a "read more" link which when clicked will open up the rest of the description of the book.

### Describe alternatives you've considered

I would like to redesign the search result cards and make them a bit smaller and more concise so that more results can be viewed at once. Also, the description of the book will be limited to 100 characters with a "read more" link which when clicked will open up the rest of the description of the book.

The cards can also be redesigned to have a glass morphism style.

### Additional context

![image](https://user-images.githubusercontent.com/78201921/194592355-62d5146e-3f24-4b33-af2e-9ae22ea15783.png)

Only one result is being viewed due to the descriptions being too long.

**Comment by AbirSantra** [comment]
I want to work on this issue under Hacktoberfest

**Comment by wasimreja** [comment]
assigned @AbirSantra

**Comment by utkarsh2709** [comment]
Hello @wasimreja, Pls assign this issue to me. I am a professional UI/UX Developer.

**Comment by wasimreja** [comment]
go ahead @utkarsh2709

**Comment by wasimreja** [comment]
@utkarsh2709 are you working on it? otherwise i'll close the issue

**Comment by utkarsh2709** [comment]
@wasimreja I am working on it.
