### ISSUE TITLE
Form shouldn't do AJAX request if input is empty

### ISSUE THREAD

**Issue by Crippler93** [wasimreja/book-finder#109]
### Describe the bug

I noticed that when input is empty, the form is still doing a request. Getting a 400 response from API.

### Steps to reproduce

1. Go to 'http://127.0.0.1:5500/index.html'
2. Leave search input empty
3. Click on search or press enter
4. The AJAX request is sent and you receive a 400 status code.

### Expected behavior

Form should not do the request if input is empty

### Screenshots

![image](https://user-images.githubusercontent.com/14883509/194603607-bb301d62-a82b-4e21-97ef-4bb6dab2c253.png)

### Desktop

- OS: Windows 10
- Browser: Microsoft Edge
- Version: 106.0.1370.34

### Smartphones

NA

**Comment by heysagnik** [comment]
Can I work on this?

**Comment by Crippler93** [comment]
> Can I work on this?

I would like to work on this, if they approve it, sorry
