### ISSUE TITLE
Adding a footer

### ISSUE THREAD

**Issue by aditi10701** [wasimreja/book-finder#114]
### Is your feature request related to a problem? Please describe.

its adds an additional functionality to the website.

### Describe the solution you'd like

add a footer to add copyright.

### Describe alternatives you've considered

nil

**Comment by mnosov622** [comment]
Hello @aditi10701 !

I would love to work on this issue. Could you please assign it to me and let me know what footer is expected ?

**Comment by abhijain2003** [comment]
hey can you assign this to me

**Comment by Urmilasc** [comment]
Hello , I want to contribute in this issue , can you please assign to me?

**Comment by disha815** [comment]
hey @aditi10701 
pls assign this issue to me

**Comment by abhijain2003** [comment]
hey it's a joint assigned so, other contributors how you are going to do please tell me

**Comment by aditi10701** [comment]
A footer of such type can be added
![image](https://user-images.githubusercontent.com/98349669/194745073-bbf489ca-fcf1-444b-8d80-1c0369ba1082.png)

**Comment by abhijain2003** [comment]
can you share social media links to be added

**Comment by aditi10701** [comment]
It will be based on the project owner details.

**Comment by wasimreja** [comment]
exclude social media links

**Comment by aditi10701** [comment]
sure

**Comment by aditi10701** [comment]
s this fine? 
![image](https://user-images.githubusercontent.com/98349669/194746699-746a869b-ef9b-4c75-833c-0c3c96221ae4.png)

**Comment by mnosov622** [comment]
Hi @wasimreja !

Why it has been reassigned? 🥲

**Comment by Ayushbajpai19** [comment]
Hello, can i work on this issue please, i would like to redesign this footer and further work on it!

**Comment by mnosov622** [comment]
Hello @wasimreja,

Could you review my PR, please ? #137 

Thank you.

**Comment by wasimreja** [comment]
> s this fine? ![image](https://user-images.githubusercontent.com/98349669/194746699-746a869b-ef9b-4c75-833c-0c3c96221ae4.png)

keep the background similar to nav bar, remove terms & conditions, privacy policy, align copyright to center

**Comment by mnosov622** [comment]
@wasimreja Hi!

Could you review my PR , please ? #137

**Comment by wasimreja** [comment]
@mnosov622 make the necessary changes as i said

**Comment by mnosov622** [comment]
> @mnosov622 make the necessary changes as i said 

Sure, got it !

**Comment by aditi10701** [comment]
is the footer fine?
![image](https://user-images.githubusercontent.com/98349669/194921949-1ac62c30-0f43-4822-a3f0-7171100f8d06.png)

**Comment by aditi10701** [comment]
> > s this fine? ![image](https://user-images.githubusercontent.com/98349669/194746699-746a869b-ef9b-4c75-833c-0c3c96221ae4.png)
> 
> keep the background similar to nav bar, remove terms & conditions, privacy policy, align copyright to center

is the footer fine?
I made the necessary changes.
![image](https://user-images.githubusercontent.com/98349669/194921949-1ac62c30-0f43-4822-a3f0-7171100f8d06.png)

**Comment by mnosov622** [comment]
Guys, maybe we all make small changes so that everyone could contribute ?

**Comment by Ayushbajpai19** [comment]
![image](https://user-images.githubusercontent.com/60637499/194942055-9477e138-09b6-4724-81b9-91ca4e6b823b.png)

This is something that I tried doing, you just need to add the links and change icons for the desired social media icons, also if you can provide links it would be great, I will do it by myself.

**Comment by rohitroy-github** [comment]
Is this issue still open to work on ?

**Comment by wasimreja** [comment]
> Is this issue still open to work on ?

yes!

**Comment by Ayushbajpai19** [comment]
Wasim bro, I kind of agree with mnosov622, we should try to make small changes, so everyone gets a chance, will you be merging my pr or should I make necessary changes as you told?

**Comment by wasimreja** [comment]
> Wasim bro, I kind of agree with mnosov622, we should try to make small changes, so everyone gets a chance, will you be merging my pr or should I make necessary changes as you told?

do the changes to footer, i'll merge it. no need to work on about page.

**Comment by mnosov622** [comment]
@wasimreja  I already did footer, could you merge my PR, please ?

Other people could fix it and make it look better.
