### ISSUE TITLE
Enhance light/dark mode toggle button

### ISSUE THREAD

**Issue by wasimreja** [wasimreja/book-finder#144]
### Is your feature request related to a problem? Please describe.

Enhance light/dark mode theme switch. 

### Describe the solution you'd like

Create minimal light/dark mode toggle button. Use this icons:
- https://fontawesome.com/icons/sun-bright?s=solid&f=classic
- https://fontawesome.com/icons/moon?s=solid&f=classic

### Describe alternatives you've considered

NA

### Additional context
Similar to this https://wasimreja.me/

**Comment by anant-strong** [comment]
@wasimreja i'd like to work on this issue

**Comment by gaurav-iitb** [comment]
can you please assign it to me

**Comment by gaurav-iitb** [comment]
@wasimreja please review my pr for this issue

**Comment by Tahree22** [comment]
Hello, I'd like to work on this issue. Could you assign this to me?
