### ISSUE TITLE
make the cards more distinguishable by adding some styles

### ISSUE THREAD

**Issue by Bibhavshah** [wasimreja/book-finder#15]
The current gap between two consecutive is not much distinguishable, as shown in the picture. 
![Screenshot (1514)](https://user-images.githubusercontent.com/78656387/193422094-264bec52-c520-403a-b866-c0465a377974.png)

By improving on this we can make the website look more beautiful and appealing.

**Comment by Bibhavshah** [comment]
@wasimreja what happened, why close?

**Comment by wasimreja** [comment]
already done

**Comment by Bibhavshah** [comment]
but it was assigned to me?
