### ISSUE TITLE
Restrict api call when there is blank string in search parameter

### ISSUE THREAD

**Issue by nilesh9836** [wasimreja/book-finder#155]
### Describe the bug

There should be no api call when user hit enter without typing any text either by typing only space

### Steps to reproduce

1. Go to page
2. click on the search icon without typing

### Expected behavior

There should be no api call when user hit enter without typing any text either by typing only space

### Screenshots

![Uploading Screenshot 2022-10-10 at 10.56.36 PM.png…]()

### Desktop

- OS: [mac]
- Browser: [chrome, safari]
- Version: [106]

### Smartphones

- Device: [iPhone6]
- OS: [iOS8.1]
- Browser [safari]
- Version [22]

**Comment by nilesh9836** [comment]
@wasimreja I have sent you a pull request please look into it. Let me know for any query

**Comment by wasimreja** [comment]
> @wasimreja I have sent you a pull request please look into it. Let me know for any query

you haven't taken pull from the upstream repository

**Comment by nilesh9836** [comment]
@wasimreja it seems that the issue is fixed.
