### ISSUE TITLE
Change the current illustration and font.

### ISSUE THREAD

**Issue by priyadarshni-jha** [wasimreja/book-finder#165]
### Is your feature request related to a problem? Please describe.

No it is not related to a problem. This feature request  is to improve the visual aspect of the website.

### Describe the solution you'd like

Replacing the current fonts and illustrations with more appealing ones.

### Describe alternatives you've considered

Finding a font hierarchy that complements the illustration change.

**Comment by wasimreja** [comment]
@priyadarshni-jha make changes on hacktoberfest branch, not main branch

**Comment by Hiresh23** [comment]
i would like to contribute

**Comment by Purva2803** [comment]
I will do some CSS changes please assign me this issue.
