### ISSUE TITLE
Add transition to the search bar

### ISSUE THREAD

**Issue by pooranjoyb** [wasimreja/book-finder#168]
### Is your feature request related to a problem? Please describe.

No its **not a problem** but it looks good when the **placeholder** in the search doesn't vanish on click.

### Describe the solution you'd like

I feel that the main attraction of the page is the title and the search bar of the page so I would like to add some of transitions to the search bar so that the placeholder doesn't vanishes on click and hence improving the UI of the search bar.

### Describe alternatives you've considered

Alternatives includes adding some other type of search bars from some frameworks like Bootstrap or Material UI.

**Comment by pooranjoyb** [comment]
Thanks a lot @wasimreja Will get into this asap.

**Comment by wasimreja** [comment]
@pooranjoyb best of luck!
