### ISSUE TITLE
adding of navbar

### ISSUE THREAD

**Issue by anuragasawa20** [wasimreja/book-finder#177]
### Is your feature request related to a problem? Please describe.

no it's not a problem . It is kind of feature which I want to add the website

### Describe the solution you'd like

I want to add navbar section with home, about us , search and faq feature 

### Describe alternatives you've considered

i will add a navbar of this type
![image](https://user-images.githubusercontent.com/99682976/195420698-bf23041c-2ff9-4d50-a3b4-033d2b66a42e.png)

### Additional context

so please assign it to me under the hacktober tag

**Comment by anuragasawa20** [comment]
Also want to add hover effect on search cards

**Comment by wasimreja** [comment]
add home, about us to navbar similar to this. no need to add hover effect on search cards
![194778588-933468ef-3d96-40f6-abb2-8b2b45dfbc47](https://user-images.githubusercontent.com/77227201/195570637-9104e69c-98d6-4222-8733-a3513923d050.png)

**Comment by Tahree22** [comment]
please assign this issue to me

**Comment by Tahree22** [comment]
I want to fix a bug on the navbar-brand (BookFinder) so that he page remains when it's clicked.

**Comment by anuragasawa20** [comment]
this is already assigned to me
