### ISSUE TITLE
Adding footer and contact us section

### ISSUE THREAD

**Issue by Simranjain06** [wasimreja/book-finder#179]
### Is your feature request related to a problem? Please describe.

I want to add a footer that includes contact details and links to social media handles and a small about us description about you website. And I also want to add some new attractive buttons to your website...

### Describe the solution you'd like

So, I am thinking as when new users come, she/he must want to know what is this website and how to use it, If users face any issues he/she wants contact details to resolve these issues.

### Describe alternatives you've considered

An alternative I consider is If you have enough details and description then you make one new contact and about us page and add links in navbar of your website..

**Comment by Simranjain06** [comment]
Hey,I want to work on this task, Can you assign it to me?

**Comment by wasimreja** [comment]
@Simranjain06 someone is already working on the footer, you can work on about page. contact page isn't needed.

**Comment by wasimreja** [comment]
@Simranjain06 someone is already working on the footer, you can work on about page #79 . contact page isn't needed.

**Comment by Purva2803** [comment]
I also want to work on this issue I will make some improvements, please assign me this issue.

**Comment by Abhay5855** [comment]
I also want to work on this issue can you assign it to me please @Simranjain06

**Comment by Abhay5855** [comment]
@wasimreja  Thanks for assigning I will get on it and propose a solution soon

**Comment by ajiteshsarangi** [comment]
Hello, I am a frontend developer and I would like to make some improvements.
