### ISSUE TITLE
Add about page

### ISSUE THREAD

**Issue by wasimreja** [wasimreja/book-finder#191]
### Is your feature request related to a problem? Please describe.

Add an about us page describing the project.

### Describe the solution you'd like

You can find the project description from `README.md`. Add home and about us links in navbar to help the user in navigating around the website. 

### Describe alternatives you've considered

You can add illustration to make it more appealing. 
https://cdn.dribbble.com/users/3942177/screenshots/10076498/book-reading_4x.jpg

### Additional context

![Book Finder](https://user-images.githubusercontent.com/77227201/196030710-fec2a1b9-4fa8-42b7-b8c9-d01e64e53218.png)

**Comment by najeebkp** [comment]
hi @wasimreja  please assign this to me
