### ISSUE TITLE
Adding a new background

### ISSUE THREAD

**Issue by KanishkDadhich** [wasimreja/book-finder#2]
## 🚀 Feature

Hey folks.
I want to add a decent background to this website, so that it looks quite a bit more captivating.
Thanks :)

**Comment by KanishkDadhich** [comment]
Hey @wasimreja 
Please assign this issue to me

**Comment by darshikaguptaa** [comment]
Hey @KanishkDadhich 
I am interested in working on this issue
Please assign this issue to me.

**Comment by vaibhavi-roy** [comment]
Hello @KanishkDadhich I am interested to work on this issue.
Please assign this to me.
Thank you

**Comment by Rituraj-13** [comment]
Hey @KanishkDadhich , I want to work on this. Can you please assign this to me?
