### ISSUE TITLE
Make about page responsive

### ISSUE THREAD

**Issue by wasimreja** [wasimreja/book-finder#200]
### Describe the bug

The about page is not responsive for small screens. 

### Expected behavior

Improve the responsiveness of about us page. 

### Screenshots

![Screenshot 2022-10-17 at 20-27-33 Book Finder](https://user-images.githubusercontent.com/77227201/196211467-c835ed39-fdd7-4cb8-9fbf-ee9d2f75fe28.png)

### Desktop

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]

**Comment by tomoyanime** [comment]
Hi @wasimreja I can work on this
