### ISSUE TITLE
Add footer in about page

### ISSUE THREAD

**Issue by wasimreja** [wasimreja/book-finder#210]
### Is your feature request related to a problem? Please describe.

Add the existing footer in about page and fix the footer for small screens. 

### Describe the solution you'd like

NA

### Describe alternatives you've considered

NA

### Additional context

![Screen Shot 2022-10-19 at 13 19 26](https://user-images.githubusercontent.com/77227201/196629432-56e5906a-fd19-4941-99f4-31dd15df58d4.png)

**Comment by Gopal2021025** [comment]
I would like to work on this issue kindly assign me .
