### ISSUE TITLE
Fix footer 

### ISSUE THREAD

**Issue by wasimreja** [wasimreja/book-finder#215]
### Describe the bug

When the user searches for a book and scrolls the screen, the footer overlay the search result card. 

### Expected behavior

The footer should not overlap the search result card.

### Screenshots

![Screenshot 2022-10-20 at 14-08-10 Book Finder](https://user-images.githubusercontent.com/77227201/196899722-04bae5fa-3a22-4715-b719-5a90eedced33.png)

![Screen Shot 2022-10-20 at 13 57 50](https://user-images.githubusercontent.com/77227201/196899261-20975adf-b86a-4165-9783-acb6ad318baf.png)

### Desktop

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]

**Comment by LeGrandMAG** [comment]
I would like to work on that issue. Can you assign it to me?

**Comment by LeGrandMAG** [comment]
@wasimreja, Thanks. I will work on it and get back to you.

**Comment by wasimreja** [comment]
all good!
