### ISSUE TITLE
Enhance dark theme color palette 

### ISSUE THREAD

**Issue by wasimreja** [wasimreja/book-finder#222]
### Is your feature request related to a problem? Please describe.

Enhance dark theme color palette with material design.

### Describe the solution you'd like

NA

### Describe alternatives you've considered

NA

**Comment by 0b51d14n217** [comment]
I'd like to take up this issue, kindly assign it to me.

**Comment by Anim3shSinha** [comment]
I would like to work to this issue. Please assign it to me.
