### ISSUE TITLE
Github icon in footer

### ISSUE THREAD

**Issue by J0SAL** [wasimreja/book-finder#228]
### Is your feature request related to a problem? Please describe.

The name looks like a simple text
![image](https://user-images.githubusercontent.com/52382282/197505527-9fb76d5f-8418-48e5-8d87-0700c3033894.png)

### Describe the solution you'd like

Add a Github icon before the name

### Describe alternatives you've considered

- Highlight the name by changing the CSS color
- add circular GitHub icon

**Comment by J0SAL** [comment]
Please assign me this issue

**Comment by Kushal-Pareek** [comment]
Please assign this issue to me. 🙏
