### ISSUE TITLE
Listening to audio explanation continues even after page refresh.

### ISSUE THREAD

**Issue by davidemmolino** [wasimreja/book-finder#237]
### Describe the bug

I tried refreshing the page after clicking to Listen since there is no way to stop the audio and after refreshing I could still hear the audio going.

### Steps to reproduce

1. Find a book
2. Click on 'Listen'
3. Refresh the page

### Expected behavior

Stop audio

### Desktop

- OS: Windows 11
- Browser: Chrome
- Version: 107.0.5304.88

### Smartphones

N/A

**Comment by wasimreja** [comment]
@davidemmolino go ahead
