### ISSUE TITLE
Footer not in right position

### ISSUE THREAD

**Issue by sajdakabir** [wasimreja/book-finder#239]
### Describe the bug

The footer is not at the bottom of the page.
https://book-finder.onrender.com/

### Expected behavior

Fottor should at the bottom. 

### Desktop

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]

**Comment by rsarthak** [comment]
![book](https://user-images.githubusercontent.com/60438849/218115536-60d39cb2-ec7e-4411-99d4-39bb8473b7bb.png)
Hey, can you elaborate the bug?
From my observation, footer is at the bottom of the page.

**Comment by wasimreja** [comment]
@sajdakabir provide screenshot

**Comment by sajdakabir** [comment]
![Screenshot from 2023-02-10 20-39-39](https://user-images.githubusercontent.com/86569763/218126953-14bf2a9c-1a6f-4e70-a292-efb4152c2edc.png)

**Comment by rsarthak** [comment]
@sajdakabir at the time of loading it is showing like this and that too for once and after that it is at the right position.

**Comment by Aryansriva** [comment]
can you assign it to me. I can fix it.

**Comment by wasimreja** [comment]
comments before 15th feb are not valid

**Comment by vermaanurag1532** [comment]
![Screenshot (437)](https://user-images.githubusercontent.com/104077846/218261306-a570d1f1-db0b-404f-b1fd-30b4e2ede2da.png)
improve the UI of footer and add responsiveness to it. Can i raise the pr so that you can review this ui.

**Comment by itsshahinhere** [comment]
I want to work on this issue under JWOC.

**Comment by manya0210** [comment]
Hello sir ..I want to contribute to this issue under jwoc

**Comment by Aniket-011** [comment]
I want to work on this issue please assign me this issue.

**Comment by PARASnagpal99** [comment]
I want to work on this . Please assign this to me .

**Comment by vermaanurag1532** [comment]
I want to work on this . Please assign this to me . And i have send the img of the UI of footer .

**Comment by Codey001** [comment]
i want to work on the issue

**Comment by SubhajitB05** [comment]
"I want to work on this issue under JWOC"

**Comment by Shreyan-12345** [comment]
I want to work please under JWOC
