### ISSUE TITLE
Fix book not found message for dark theme 

### ISSUE THREAD

**Issue by wasimreja** [wasimreja/book-finder#241]
### Describe the bug

Book not found message is not clearly readable in dark theme. 

### Expected behavior

Change text color to lighter. 

### Screenshots

![Screenshot 2023-02-11 at 00-26-47 Book Finder](https://user-images.githubusercontent.com/77227201/218177314-3a1f2b75-f798-40e5-94bd-4cc3a5783e6d.png)

### Desktop

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]

**Comment by AbhiPatel10** [comment]
@wasimreja I would like to work on this issue 🙋‍♂️

**Comment by loki1205** [comment]
Hi, I would love to work on this issue. Please, assign this to me.

**Comment by SheriffHobo** [comment]
I would like to work this issue.

**Comment by wasimreja** [comment]
comments before 15th feb are not valid

**Comment by PuspenduGit** [comment]
Assign this to me

**Comment by singhalaman23** [comment]
"I want to work on this issue under JWOC"

**Comment by ritika728** [comment]
Hey, I want to work on this issue under JWOC

**Comment by vk20july** [comment]
I want to work on this issue under JWOC

**Comment by Arbtrage** [comment]
Hey @wasimreja , can I work on this issue..

**Comment by AgnishaDe** [comment]
I want to work on this issue under JWOC

**Comment by Aniket-011** [comment]
I want to work on this issue please assign me this issue.

**Comment by purbakundu** [comment]
I want to solve this issue
