### ISSUE TITLE
Add stop functionality to listen button

### ISSUE THREAD

**Issue by wasimreja** [wasimreja/book-finder#242]
### Is your feature request related to a problem? Please describe.

If you press listen button then you can't stop the audio. It will continue playing. 

### Describe the solution you'd like

Add stop functionality to listen button.

### Describe alternatives you've considered

NA

**Comment by Laxmankohar** [comment]
Hey @wasimreja  I would like to work on this issue. Can you please assign this issue to me.

**Comment by wasimreja** [comment]
comments before 15th feb are not valid

**Comment by vk20july** [comment]
I want to work on this issue under JWOC

**Comment by Laxmankohar** [comment]
Hey @wasimreja I would like to work on this issue. Can you please assign this issue to me.

**Comment by Sarita-021** [comment]
Hi @wasimreja I would like to contribute to the issue .  Can you please assign it to me . underJWOC
