### ISSUE TITLE
Add contributors.json file

### ISSUE THREAD

**Issue by wasimreja** [wasimreja/book-finder#244]
### 📚 Documentation

We need to store all the contributors details. 
```
{
  "profiles": [
    {
      "name": "Wasim Reja",
      "avatarUrl": "https://avatars.githubusercontent.com/u/77227201?v=4",
      "github": "wasimreja",
      "twitter": "_wasimreja"
    }
 ]
}
```

### Additional context

For avatar, go to user profile, right click on image and copy image link. 
Twitter is optional.

**Comment by Sowham-3098** [comment]
@wasimreja Please assign this task to me

**Comment by Sowham-3098** [comment]
@wasimreja Please assign this task to me

**Comment by purbakundu** [comment]
i want to contribute
