### ISSUE TITLE
Fix loading spinner

### ISSUE THREAD

**Issue by wasimreja** [wasimreja/book-finder#248]
### Describe the bug

Fix loading spinner overlapping issue for small screens. 

### Expected behavior

The loading spinner and result card shouldn't overlap. 

### Screenshots

![Screen Shot 2023-02-14 at 16 11 55](https://user-images.githubusercontent.com/77227201/218715094-3052755c-e52d-44ea-9c85-6bffbbdc5437.png)

### Desktop

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]

**Comment by realsh9dy** [comment]
Please assign me this issue

**Comment by kushaljgec2025** [comment]
I want to work on this under JWOC

**Comment by SarveshGholap** [comment]
I would like to work on this
