### ISSUE TITLE
Change footer background

### ISSUE THREAD

**Issue by wasimreja** [wasimreja/book-finder#249]
### Is your feature request related to a problem? Please describe.

Whether it is light theme or dark, background of the footer is dark. 

### Describe the solution you'd like

Change the footer background for light theme. 

### Describe alternatives you've considered

NA

### Additional context

Set the footer background color to `var(--nav-color)`. Change the footer icons background color to `rgb(219, 211, 211)` for light theme.

**Comment by realsh9dy** [comment]
Please assign me this issue

**Comment by Atul-8115** [comment]
I want to work on this issue please assign it to me

**Comment by SubhajitB05** [comment]
I want to contribute on this issue under JWOC

**Comment by purbakundu** [comment]
i want to contribute

**Comment by Mayukh-Ghosh** [comment]
I want to work on this issue under JWOC.

**Comment by Sinchan26** [comment]
hey i raised the issue first in discord channel..i should be assigned for this

**Comment by sandeeprawat28** [comment]
Please give me this issue, I will make it interactive and user-friendly.
