### ISSUE TITLE
Use semantic header tag

### ISSUE THREAD

**Issue by EmmaDawsonDev** [wasimreja/book-finder#25]
## Describe the Bug 🐛

```<div class="header">``` should be renamed to ```<header class="header>```

**Comment by nishtha53** [comment]
Can u please assign to me? @EmmaDawsonDev

**Comment by nishtha53** [comment]
@EmmaDawsonDev please can u check my PR and approve it.

**Comment by EmmaDawsonDev** [comment]
It's not my repo so I can't assign unfortunately.

**Comment by nishtha53** [comment]
oh okay 
@wasimreja  please can u assign to me?

**Comment by nishtha53** [comment]
@wasimreja it is already done. Could you please check my PR. I have removed vscode settings file too.

**Comment by EmmaDawsonDev** [comment]
Please let @nishtha53 take the issue. I was just trying to help others find good first issues

**Comment by nishtha53** [comment]
@EmmaDawsonDev Thankyou. It got resolved. 
@wasimreja please close this issue.
