### ISSUE TITLE
Add social icons to footer

### ISSUE THREAD

**Issue by wasimreja** [wasimreja/book-finder#250]
### Is your feature request related to a problem? Please describe.

Add twitter, linkedin and instagram icon to the footer.

### Describe the solution you'd like

Similar to this.
![Screen Shot 2023-02-15 at 03 28 09](https://user-images.githubusercontent.com/77227201/218873085-960ff103-7746-41aa-9b62-e2a00ffd52b2.png)

### Describe alternatives you've considered

NA

**Comment by shreyanka155** [comment]
I want to work on this issue under JWOC.

**Comment by vk20july** [comment]
I want to work on this issue under JWOC

**Comment by AgnishaDe** [comment]
I want to contribute on this issue under jwoc

**Comment by Swadeshit27** [comment]
I want to work on this issue under JWOC

**Comment by Harry629** [comment]
Please assign me this issue under JWOC

**Comment by i-am-SnehaChauhan** [comment]
"I want to work on this issue under JWOC"
Please assign me

**Comment by vamsikrishnarh7** [comment]
I want to work on this issue under JWOC.
Please assign me

**Comment by mayurimahto** [comment]
I would like to work on this issue under JWOC

**Comment by wasimreja** [comment]
assigned @shreyanka155 if fails to do in the given period, will assign @AgnishaDe

**Comment by kushaljgec2025** [comment]
I want to do this under JWOC

**Comment by Mayukh-Ghosh** [comment]
I want to work on this issue under JWOC.

**Comment by Pritam991** [comment]
i am working on this.

**Comment by dibyendu02** [comment]
I wanna work on this under jwoc

**Comment by sandeeprawat28** [comment]
Please give me this issue, I will make it interactive and user-friendly.
