### ISSUE TITLE
Search and results divs should be wrapped with main tag

### ISSUE THREAD

**Issue by EmmaDawsonDev** [wasimreja/book-finder#26]
## Describe the Bug 🐛

The ```<div class="search>``` and ```<div class="results>``` should be wrapped in a ```<main>``` tag

**Comment by dreymotoh** [comment]
can you assign this issue to me?

**Comment by ShorunTech** [comment]
Can i work on this.

**Comment by nishtha53** [comment]
can i work on this?

**Comment by EmmaDawsonDev** [comment]
Please assign to someone else. I've already got my 4 hacktoberfest PRs and was just trying to help others by finding good first issues

**Comment by wasimreja** [comment]
@nishtha53 would you like to work on this?

**Comment by wasimreja** [comment]
@dreymotoh go ahead

**Comment by nishtha53** [comment]
@wasimreja yes I can work on this. Please assign to me!

**Comment by nishtha53** [comment]
@wasimreja Please check PR.
