### ISSUE TITLE
Design the about us page

### ISSUE THREAD

**Issue by Shreyan-12345** [wasimreja/book-finder#261]
### Is your feature request related to a problem? Please describe.

designing the About Us page

### Describe the solution you'd like

to make the UI bit beautiful of about us

### Describe alternatives you've considered

Adding more styles and css

**Comment by Shreyan-12345** [comment]
@wasimreja pls assign me this under JWOC

**Comment by wasimreja** [comment]
go ahead @Shreyan-12345
