### ISSUE TITLE
Fix overlapping isssue with the footer

### ISSUE THREAD

**Issue by wasimreja** [wasimreja/book-finder#263]
### Describe the bug

Fix the overlapping issue with the footer. 

### Expected behavior

It shouldn't overlap. 

### Screenshots

![Screen Shot 2023-02-16 at 01 44 46](https://user-images.githubusercontent.com/77227201/219143296-a69c6b4b-c1bd-49e0-bd47-e0b72ffb87fe.png)
![Screenshot 2023-02-16 at 01-41-48 Book Finder](https://user-images.githubusercontent.com/77227201/219143317-4fafb8bb-49a1-428c-8d7d-eecb73dead03.png)
![Screen Shot 2023-02-16 at 01 40 05](https://user-images.githubusercontent.com/77227201/219143337-17291cc8-2f97-4c24-a11c-bde86a09b316.png)
![Screenshot 2023-02-16 at 01-41-34 Book Finder](https://user-images.githubusercontent.com/77227201/219143331-9e69d8e7-68cb-48e8-9ab0-489b26b610eb.png)
![Screen Shot 2023-02-16 at 01 39 48](https://user-images.githubusercontent.com/77227201/219143351-369e371c-e4b8-40cc-9a7e-d06fa742e40c.png)

### Desktop

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]

**Comment by Laxmankohar** [comment]
Hey @wasimreja i would like to work on this issue under JWOC. Can you assign it to me?

**Comment by arjunchoudhury07** [comment]
I would like to contribute

**Comment by wasimreja** [comment]
assigned @Laxmankohar if fails to do in the given period, will assign @arjunchoudhury07

**Comment by Laxmankohar** [comment]
Hey @wasimreja , Please have a look.

![image](https://user-images.githubusercontent.com/73365025/219360076-936e7b2a-6fc6-43f2-b58c-93e4db2cff7c.png)
![image](https://user-images.githubusercontent.com/73365025/219360094-7f51f47a-56cc-4293-8556-da5f7a2c81fb.png)

**Comment by Laxmankohar** [comment]
So, I am going to make a pull request.

**Comment by wasimreja** [comment]
@arjunchoudhury07 go ahead

![Screenshot 2023-02-18 at 18-34-44 Book Finder](https://user-images.githubusercontent.com/77227201/219867415-07b29a93-6404-4be0-b59a-0ed1a0f15bc5.png) 
![Screenshot 2023-02-18 at 18-35-59 Book Finder](https://user-images.githubusercontent.com/77227201/219867410-a5e5e6fe-9a37-42e2-92e0-ee2392147763.png)
![Screenshot 2023-02-18 at 18-34-53 Book Finder](https://user-images.githubusercontent.com/77227201/219867414-86794e74-6cea-4946-af05-40e24f71a5bb.png)
