### ISSUE TITLE
Add language change tab

### ISSUE THREAD

**Issue by ayushanand308** [wasimreja/book-finder#269]
### Is your feature request related to a problem? Please describe.

If someone does not know English then he can not use the website.

### Describe the solution you'd like

We can add a section on the navbar with some language options and then when user selects a particular language, we can translate the page to that language

### Describe alternatives you've considered

No alternatives.

**Comment by ayushanand308** [comment]
@devwasim Please assign me this issue under JWOC if you think the issue is reasonable.

**Comment by ayushanand308** [comment]
Will keep you updated on the progress.

**Comment by SarveshGholap** [comment]
I want to work on this issue under jwoc

**Comment by deepbeatz** [comment]
I want to work on this under JWOC

**Comment by ayushanand308** [comment]
![image](https://user-images.githubusercontent.com/99035102/219940789-99155f6d-7310-4e6c-b676-6230c9e18d6a.png)

**Comment by ayushanand308** [comment]
@wasimreja I was testing the feature on a separate page. I am not able to remove the prompt at the top. I used inspect page and tried to hide the class this prompt belongs to with css but could not do it. Any suggestions on how to remove it.

**Comment by ayushanand308** [comment]
Using google translate API here.

**Comment by ayushanand308** [comment]
![image](https://user-images.githubusercontent.com/99035102/220113037-6cb61533-90c2-46d7-9fbf-6d57cc2d1e3f.png)

**Comment by ManasaKaza** [comment]
I want to work on this issue under JWOC
