### ISSUE TITLE
An animated Landing page for website on opening

### ISSUE THREAD

**Issue by AK-shat-JAIN** [wasimreja/book-finder#293]
### Is your feature request related to a problem? Please describe.

The landing page looks very normal
Want to add an animation effect in it such that the text "book finder" will animate and come like in this website
https://ak-shat-jain.github.io/FoodGenix/
that's also created by me

### Describe the solution you'd like

create an CVG on figma and animate it using css

### Describe alternatives you've considered

after animation landing page automatically redirects to index page after 3.5 seconds

**Comment by pooranjoyb** [comment]
Hey @devwasim @wasimreja I would like to work in this issue under **JWOC 2023**. Would be glad if you could assign this issue to me. Thanks. :)

**Comment by AK-shat-JAIN** [comment]
Hello @wasimreja,
It will look great as a landing page 

I first create an SVG from figma and import it into landing page and animate it using css

**Comment by priyanka1551** [comment]
I want to work on this issue under JWOC @wasimreja

**Comment by AK-shat-JAIN** [comment]
Hello @wasimreja Sr 
I have created SVG image of text from figma 

![image](https://user-images.githubusercontent.com/84455686/221032572-5ab24819-6015-4c80-910d-9d00c4413f22.png)

and I am looking to work in a Background same as that of Dark mode so as to match the theme with a white border 

![image](https://user-images.githubusercontent.com/84455686/221032781-cd096f3c-c159-4a4a-934d-92836bb4db23.png)

**Comment by Awesomeasma** [comment]
@wasimreja 
I would like to work on this under JWOC.

**Comment by AK-shat-JAIN** [comment]
Its Done already @Awesomeasma 
@wasimreja Sr please review the PR
