### ISSUE TITLE
Multiple body tags

### ISSUE THREAD

**Issue by wasimreja** [wasimreja/book-finder#294]
### Describe the bug

An HTML document can only have one body tag. Having multiple body tags means that your document is not valid HTML. 

### Expected behavior

Remove the duplicate tag. 

### Desktop

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]

**Comment by TuhinBanerjee31** [comment]
Can I get assigned to this issue under JWOC?

**Comment by vk20july** [comment]
I want to work on this issue under JWOC
