### ISSUE TITLE
Error message not readable in light theme

### ISSUE THREAD

**Issue by wasimreja** [wasimreja/book-finder#295]
### Describe the bug

Error message is not readable in light theme.

### Expected behavior

Fix error message color for light theme.

### Screenshots

![Screenshot 2023-02-23 at 20-08-41 Book Finder](https://user-images.githubusercontent.com/77227201/220938437-222e48f1-6951-4ccc-bc3d-dc8325e4fe92.png)

### Desktop

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]

**Comment by sayandippaul** [comment]
hello i found this project interesting .pls assign this issue to me

**Comment by vk20july** [comment]
I want to work on this issue under JWOC
sir this is the correct way for requesting

**Comment by sayandippaul** [comment]
i want to work on this issue under JWOC

**Comment by Priyamakeshwari** [comment]
I would like to work on this issue under JWOC
