### ISSUE TITLE
Adding a preloader

### ISSUE THREAD

**Issue by ritika728** [wasimreja/book-finder#298]
### Is your feature request related to a problem? Please describe.

Hey, I would like to open this issue under JWOC. 

### Describe the solution you'd like

I wish to add an amazing pre-loader of a book to all the pages of the website. 

### Describe alternatives you've considered

-

**Comment by ritika728** [comment]
I'll be adding a loader like this, which will fade away as soon as the page loads.
Let me know if I can work on this issue. Thank you!
![eBook](https://user-images.githubusercontent.com/91181981/221088945-7051c339-fe7f-4ab5-b704-0fdd0c335586.gif)

**Comment by wasimreja** [comment]
you can work on other issues.
