### ISSUE TITLE
Create a 404 error page

### ISSUE THREAD

**Issue by wasimreja** [wasimreja/book-finder#302]
### Is your feature request related to a problem? Please describe.

There is no 404 error page that tells users the requested page is unavailable or, in some cases, doesn’t exist.

### Describe the solution you'd like

Create a custom 404 error page with cool animations. 

### Describe alternatives you've considered

NA

**Comment by TuhinBanerjee31** [comment]
I want to work on this issue under JWOC

**Comment by Awesomeasma** [comment]
I would like to work on this issue under JWOC.

**Comment by ManasaKaza** [comment]
I would like to work on this issue under JWOC
