### ISSUE TITLE
Create contact us page

### ISSUE THREAD

**Issue by wasimreja** [wasimreja/book-finder#304]
### Is your feature request related to a problem? Please describe.

Create a contact us page. 

### Describe the solution you'd like

Add a contact form and also add social icons. 

### Describe alternatives you've considered

NA

**Comment by itsshahinhere** [comment]
hello i would like to work on this issue under jwoc.
can u please share the theme or wirefram about how it want to look like ?

**Comment by khushimarothi** [comment]
I am interested to work on this issues under JWOC

**Comment by wasimreja** [comment]
![Screenshot 2023-03-01 at 13-28-49 GDSC JGEC](https://user-images.githubusercontent.com/77227201/222079019-6e89e840-b221-4a0b-a682-b416c41454d2.png)

**Comment by wasimreja** [comment]
> hello i would like to work on this issue under jwoc. can u please share the theme or wirefram about how it want to look like ?

https://gdscjgec.github.io/pages/contact.html

**Comment by wasimreja** [comment]
assigned @itsshahinhere. if fails to do in the given period, will assign @khushimarothi

**Comment by wasimreja** [comment]
leave it. no need to create contact us page.
