### ISSUE TITLE
Adding Glass UI to the Navbar

### ISSUE THREAD

**Issue by pooranjoyb** [wasimreja/book-finder#306]
### Is your feature request related to a problem? Please describe.

No, its not a problem, but glass UI in navbar looks really professional.

### Describe the solution you'd like

I would like ot make some of the CSS changes in order to accomplish my task

### Describe alternatives you've considered

We could use some library or components.

### Additional context

I would like to work on this issue under JWOC 2023. Please assign @wasimreja @devwasim  😄

**Comment by wasimreja** [comment]
adding glass ui to the nav bar won't look good as compared to the overall ui.

**Comment by pooranjoyb** [comment]
> adding glass ui to the nav bar won't look good as compared to the overall ui. 

Oke. 👍
