### ISSUE TITLE
Redirect book not found to 404 page

### ISSUE THREAD

**Issue by wasimreja** [wasimreja/book-finder#311]
### Is your feature request related to a problem? Please describe.

When you search for a book that couldn't be found, it shows book not found message.

### Describe the solution you'd like

Redirect it to the 404 error page. 

### Describe alternatives you've considered

NA

**Comment by realsh9dy** [comment]
Please assign me this issue

**Comment by VelialCypher** [comment]
Hello!
Can I fix this?

**Comment by Awesomeasma** [comment]
I would like to work on this issue under JWOC.
