### ISSUE TITLE
Create a contact us page

### ISSUE THREAD

**Issue by khushimarothi** [wasimreja/book-finder#317]
### Is your feature request related to a problem? Please describe.

I want to add a contact us page with a form where user can share feedback.

### Describe the solution you'd like

will add a new page with form and contact details.

### Describe alternatives you've considered

N/A

### Additional context

Please assign under JWOC

**Comment by khushimarothi** [comment]
should I make it responsive or not?

**Comment by wasimreja** [comment]
make it responsive
