### ISSUE TITLE
Create features page

### ISSUE THREAD

**Issue by wasimreja** [wasimreja/book-finder#318]
### Is your feature request related to a problem? Please describe.

Create features page. 

### Describe the solution you'd like

This is the prototype. You can find the illustrations in `img` folder.
 
![Features](https://user-images.githubusercontent.com/77227201/223869303-d7d91888-5cfe-45e3-8458-917705b57cf1.png)

### Describe alternatives you've considered

NA

**Comment by vk20july** [comment]
I want to work on this issue under jwoc

**Comment by TuhinBanerjee31** [comment]
I want to work on this issue under JWOC

**Comment by itsshahinhere** [comment]
I want to work on this issue under JWOC
