### ISSUE TITLE
A testimonial  should be added

### ISSUE THREAD

**Issue by Ritu-2001** [wasimreja/book-finder#325]
### Is your feature request related to a problem? Please describe.

i want to add a testimonial 

### Describe the solution you'd like

i want to add testimonial section to enhance it's features

### Describe alternatives you've considered

add a testimonial section where anyone can rate it 

### Additional context

can you please assign me for this issue under jwoc

**Comment by wasimreja** [comment]
no need to add testimonial. you can work on other issues.
