### ISSUE TITLE
Contact form Validation

### ISSUE THREAD

**Issue by ritika728** [wasimreja/book-finder#326]
### Describe the bug

Hey @wasimreja , I would like to open this issue under JWOC.

### Expected behavior

 I wish to add validation to the contact form with the help of JavaScript. Kindly assign

### Desktop

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]

**Comment by wasimreja** [comment]
@ritika728 it would be better if you could revamp the contact page. 
https://gdscjgec.github.io/pages/contact.html
