### ISSUE TITLE
Faq illustration

### ISSUE THREAD

**Issue by ritika728** [wasimreja/book-finder#349]
### Describe the bug

Hey @wasimreja, I would like to open this issue under JWOC. 

![photo](https://user-images.githubusercontent.com/91181981/225025208-33757d0c-522d-4ed3-a591-8c61e396541f.png)

### Expected behavior

-

### Screenshots

This illustration is not looking good with a white background in dark mode. I wish to improve this

### Desktop

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]

**Comment by wasimreja** [comment]
@ritika728 add one more question in faq. if anyone wants to contribute and put the link of the repository.

**Comment by Prateek556** [comment]
I want to contribute this issue under JWOC
