### ISSUE TITLE
Display results in a grid

### ISSUE THREAD

**Issue by Sir-Martin-Esq-III** [wasimreja/book-finder#4]
## 🚀 Feature

Display results in a responsive grid so that it is easier to navigate and view all the results.

It could perhaps display a "card" for each book and on hover would display more information about the book

**Comment by wasimreja** [comment]
all the best @Sir-Martin-Esq-III

**Comment by saroshfarhan** [comment]
@Sir-Martin-Esq-III @wasimreja I have a small suggestion for this, on top of displaying results in a grid, we can also lessen the size of the search bar and banner image (maybe move it as a navbar) after the first search and then each subsequent search will display the results below navbar search (more like how google does it). I can quickly provide a mock UI if we can have it as a no-code PR. Do let me know if it works for you. Cheers!

**Comment by wasimreja** [comment]
@saroshfarhan yeah it would be great!

**Comment by saroshfarhan** [comment]
@wasimreja should I open a new issue or raise a PR on this issue, how do I hand-over the design files?

**Comment by wasimreja** [comment]
@saroshfarhan raise a PR

**Comment by wasimreja** [comment]
@saroshfarhan raise a pr

**Comment by mitpancholi98** [comment]
Oops! I accidentally used table instead of grid in my pr. 

Didn't know @saroshfarhan was working. Sorry ! @wasimreja @saroshfarhan

**Comment by Sir-Martin-Esq-III** [comment]
> Oops! I accidentally used table instead of grid in my pr.
> 
> Didn't know @saroshfarhan was working. Sorry ! @wasimreja @saroshfarhan

No offence man but this issue was assigned to me, Im sure there's plenty of other issue's you could have put your hard work towards :)
