### ISSUE TITLE
A dark mode feature

### ISSUE THREAD

**Issue by Ryukemeister** [wasimreja/book-finder#46]
## 🚀 Feature

**I'd like to propose a dark mode button on the top right corner of the landing page**

- By toggling our dark mode button, our user can switch between the original light background to a dark black background while the title would change to a white color.
-  The dark mode would look something like this with a button at the top right corner

![Dark mode](https://user-images.githubusercontent.com/86043008/193464322-75ec284d-79a3-47b3-aca4-c1889ace9c9a.jpg)
- @wasimreja  please assign this feature to me.

**Comment by wasimreja** [comment]
already raised this issue before
