### ISSUE TITLE
Adding a Modern Scrollbar

### ISSUE THREAD

**Issue by KiranAminPanjwani** [wasimreja/book-finder#52]
## 🚀 Feature

I want to add a **scroll progress bar**, which is generally seen on modern websites, which would be a good addition to this website.

I'm a participant in Hacktoberfest, kindly assign this issue to me. Thank you.😊

**Is your feature request related to a problem? Please describe.**

I have noticed that after searching for a book, It shows a variety of books to the user. And the existing Scrollbar is very _boring_.

**Describe the solution you'd like**

I would like to add a modern scrollbar like this:

![image](https://user-images.githubusercontent.com/90326051/193468640-e0a4fe0f-1b6a-423c-a3d5-0acc78250651.png)

**Additional context**

![image](https://user-images.githubusercontent.com/90326051/193468601-1da2ed0c-7c66-46e6-97df-1ea848558546.png)

**Comment by wasimreja** [comment]
@KiranAminPanjwani go ahead
