### ISSUE TITLE
Adding a scroll up button when scrolling down would help to navigate to top instantly

### ISSUE THREAD

**Issue by Keshab0100** [wasimreja/book-finder#59]
## 🚀 Feature

**A clear and concise description of what the feature is.**

A scroll to top button would be convenient and improve the overall UX of the website.

**Is your feature request related to a problem? Please describe.**
If a user scrolls down and wants to search another book he/she has to scroll all the way back up.

**Comment by Keshab0100** [comment]
Please check my pull request #60 and consider it for hacktoberfest 2022

**Comment by srummanf** [comment]
Can you assign this to me @wasimreja I m free and will work on this now
