### ISSUE TITLE
Create a Light and Dark Mode 

### ISSUE THREAD

**Issue by aaheli8** [wasimreja/book-finder#7]
## 🚀 Feature
Add a switch to change light mode to dark mode and vice versa.

**Comment by jkol7** [comment]
I would like to work on this please.

**Comment by parth-verma7** [comment]
@aaheli8 I would like to work upon this issue, can you please assign it to me?

**Comment by wasimreja** [comment]
@aaheli8 go ahead

**Comment by KanishkDadhich** [comment]
Hey @wasimreja .
I would like to work on this  issue, if nobody's working on it currently.

**Comment by Aarav238** [comment]
I would like to work on this issue if it is free . @wasimreja

**Comment by aaheli8** [comment]
I am working on this issue
