### ISSUE TITLE
Changing background of home page

### ISSUE THREAD

**Issue by Vanshiii203** [wasimreja/book-finder#77]
### Is your feature request related to a problem? Please describe.

A better background image could be set 

### Describe the solution you'd like

I would like to change the background 

### Describe alternatives you've considered

![Screenshot (452)](https://user-images.githubusercontent.com/94471189/193761704-639f773a-5da9-4a69-801b-0a683140ad03.png)
![Screenshot (453)](https://user-images.githubusercontent.com/94471189/193761726-f82d9d35-0633-490e-b7f4-e4379a9e26fb.png)
![Screenshot (454)](https://user-images.githubusercontent.com/94471189/193761735-33d2353d-62b3-4ef0-88ca-55d74d78e090.png)
![Screenshot (455)](https://user-images.githubusercontent.com/94471189/193761739-a059d451-3477-4c45-a9fc-597cbe88833b.png)

**Comment by wasimreja** [comment]
@Vanshiii203 raise the pr in hacktoberfest branch not main branch
