### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by Wangata** [wasimreja/book-finder#79]
### Is your feature request related to a problem? Please describe.

I love the idea, and when I first opened the website I didn't know what it does, my feature is related to adding an new About page to tell the visitor about book finder a

### Describe the solution you'd like

Add an About page

### Describe alternatives you've considered

Add an About page

**Comment by Ayushbajpai19** [comment]
Hello, can i work on this issue please?

**Comment by Wangata** [comment]
Apologies I've been away, I have worked on the issue pushing it shortly,

**Comment by wasimreja** [comment]
> Apologies I've been away, I have worked on the issue pushing it shortly,

okiee, best of luck

**Comment by Wangata** [comment]
hey, bro, I have made the required changes but since I am new to git and GitHub I am finding it hard to commit push the changes again after I have updated the branch, and doing all the possible git commands doesn't seem to fix the issues. 
![image](https://user-images.githubusercontent.com/13100730/194778588-933468ef-3d96-40f6-abb2-8b2b45dfbc47.png)

and also this is the error I am getting in my terminal when trying to push the changes i have made
PS C:\Users\marti\OneDrive\Desktop\Bookfinder\book-finder> git push -u origin about
To https://github.com/Wangata/book-finder.git
 ! [rejected]        about -> about (non-fast-forward)
error: failed to push some refs to 'https://github.com/Wangata/book-finder.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

I would really appreciate your input on this @wasimreja

**Comment by wasimreja** [comment]
@Wangata always take a pull from the upstream repository to your main branch
```
git pull upstream main

**Comment by Wangata** [comment]
Hi, @Ayushbajpai19 I will unassign this issue as I try to figure out git so that I don't interfere with the main branch. So feel free to take it up. Thanks

**Comment by Ayushbajpai19** [comment]
Yes, please assign it to me :)

**Comment by Ayushbajpai19** [comment]
Can you open this issue, it shows the issue as closed, also please label it with hacktoberfest, thanks you :)

**Comment by Ayushbajpai19** [comment]
@wasimreja can I add the following text to the about page?

BookFinder is your go-to place for all kinds of book-related searches, need to read a book but don't know where to find it?
We got your back! Started in 2022, we are an open-source free search engine with over a million books and more to find out.
Here you won't just be able to read books but also listen to them. So what are you waiting for, Search your favorite book right now!

**Comment by wasimreja** [comment]
@Ayushbajpai19 all good

**Comment by Ayushbajpai19** [comment]
Hey @wasimreja i am somehow not able to push my changes, can you help me a little bit?

**Comment by wasimreja** [comment]
yeah sure! as i can see you're trying to merging commits into main branch from hacktoberfest branch. clone main branch, create a new branch for yourself and make necessary changes then push the committed changes in your feature branch to your remote repo

> Hey @wasimreja i am somehow not able to push my changes, can you help me a little bit?

**Comment by Ayushbajpai19** [comment]
I have already made all the changes but am not able to commit, if you could open upload files section, I ould be able to commit changes
