### ISSUE TITLE
Add fevicon 

### ISSUE THREAD

**Issue by Anjali2201** [wasimreja/book-finder#9]
## 🚀 Feature

Fevicon logo in tab icon

**Comment by darshikaguptaa** [comment]
@Anjali2201 can you please assign this issue to me and also send the logo to be added.

**Comment by saiwali** [comment]
@Anjali2201  I want to work on this issue  could u please assaign this task to me??

**Comment by Bibhavshah** [comment]
Can I work on this issue please?

**Comment by saiwali** [comment]
@Anjali2201 I tried a favicon . Hope u like it!

**Comment by jbecker7** [comment]
I am not seeing any sort of favicon right now on the onrender. @Anjali2201 can you please let me know what you would like the favicon to be? I can fix it right away.

**Comment by Bibhavshah** [comment]
Can I try working on it?
