### ISSUE TITLE
Add a floating back to top button

### ISSUE THREAD

**Issue by wasimreja** [wasimreja/book-finder#90]
### Is your feature request related to a problem? Please describe.

Add a floating back to top button like this https://codeconvey.com/floating-back-to-top-button-html/ so that the user doesn't have to scroll through the whole page and get on the top of the page just by clicking on the button.

### Describe the solution you'd like

bla bla bla

### Describe alternatives you've considered

bla bla bla

**Comment by SainathPoojary** [comment]
Hey @wasimreja, I want to work on this. Can you please assign it to me?

**Comment by abel-otegbola** [comment]
Hi @wasimreja  nice project you have here.
Can I work on it.

**Comment by DevilzzNikhil** [comment]
@wasimreja  can i work on this ??

**Comment by debjitnandan05** [comment]
Hey!! @wasimreja I want to work on this project with you. Can you please assign it to me?

**Comment by cu8code** [comment]
Please check my [PR](https://github.com/wasimreja/book-finder/pull/92#issue-1400713808). Please let me know if anything needs to be added.
