### ISSUE TITLE
Add a loading spinner 

### ISSUE THREAD

**Issue by wasimreja** [wasimreja/book-finder#93]
### Is your feature request related to a problem? Please describe.

Currently if you search for a book and you have slow internet there is no indication that it fetches the data based on your input.

### Describe the solution you'd like

Add a animated loading spinner.

### Describe alternatives you've considered

https://github.com/jlong/css-spinners

**Comment by SOUMYADIP76** [comment]
I

**Comment by chnrv99** [comment]
whats the logo and the dimensions for the loading spinner? anything else on how it should look , etc?

**Comment by SOUMYADIP76** [comment]
Should I commit to the main branch or to the hacktoberfest branch @wasimreja  ?

**Comment by wasimreja** [comment]
main branch
