### ISSUE TITLE
Fix listen button

### ISSUE THREAD

**Issue by wasimreja** [wasimreja/book-finder#94]
### Describe the bug

Listen button is not working properly on few browsers. 

### Expected behavior

Fix listen button so that user can listen description about a book. 

### Desktop

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]

**Comment by najeebkp** [comment]
Hi @wasimreja please assign this to me. I'll take care.

**Comment by wasimreja** [comment]
all the best @najeebkp
