### ISSUE TITLE
Title and image overlapping the header in the scroll

### ISSUE THREAD

**Issue by IsabellaSoares** [wasimreja/book-finder#96]
### Describe the bug

When the user searches for a book and scrolls the screen, the title and the image of the book overlay the application header.

### Steps to reproduce

1. Go to the home page
2. Click on the search bar
3. Search for "The reed queen" book
4. Scroll down to the bottom of the page
5. See that the title and the image overlap with the header

### Expected behavior

The title and image should not overlap the header.

### Screenshots

![Screen Shot 2022-10-07 at 10 33 38](https://user-images.githubusercontent.com/32148199/194569159-a0c3ff95-6807-4a45-854b-681256d92503.png)

### Desktop

- OS: MacOS
- Browser: Chrome

### Smartphones

Not applicable

**Comment by IsabellaSoares** [comment]
Hi @wasimreja, I want to work with this. Can you assign this to me?

**Comment by Yugal308** [comment]
Hi @wasimreja, I want to work on this as well. Can you assign this to me as well?
