### ISSUE TITLE
Redirect to the home page by clicking on the header logo

### ISSUE THREAD

**Issue by IsabellaSoares** [wasimreja/book-finder#99]
### Is your feature request related to a problem? Please describe.

When the user clicks on the logo, he should be redirected to the home page, clearing his previous search history. Currently this is not the case, and it is only possible to do this redirection by clearing the URL.

https://user-images.githubusercontent.com/32148199/194570139-e2bcd0b8-8ad2-4992-8b26-b4362c9f60c7.mov

### Describe the solution you'd like

When the user clicks on the logo, he should be redirected to the home page, clearing his previous search history.

### Describe alternatives you've considered

Not applicable.

**Comment by IsabellaSoares** [comment]
Hi @wasimreja! I want to work with this, can you assign this to me?

**Comment by wasimreja** [comment]
assigned @IsabellaSoares

**Comment by anushkamandal25** [comment]
Hello! Is this issue applicable for hacktoberfest? This is my first time in hacktoberfest. I want to contribute in this issue. So please assign me.

**Comment by wasimreja** [comment]
@IsabellaSoares what's the update?

**Comment by manishgupta416** [comment]
Can you assign to me?
